// Bilingual editorial content shared by the homepage and catalogue.
export const siteCopy = {
  en: {
    solutions: "Our solutions",
    story: "Our story",
    partners: "Our partners",
    contact: "Let’s grow together",
    eyebrow: "AGRICULTURE. CONNECTED.",
    title: "Rooted in trust.",
    accent: "Growing possibilities.",
    intro:
      "Connecting growers in Tajikistan with world-class agricultural solutions. From the first seed to the next harvest.",
    explore: "Explore our solutions",
    discover: "Discover Nihol",
    scroll: "SCROLL TO EXPLORE",
    since: "CULTIVATING PARTNERSHIPS SINCE 2016",
    pause: "Pause motion",
    play: "Resume motion",
    trusted: "GLOBAL EXPERTISE. LOCAL ROOTS.",
    solutionEyebrow: "01 / WHAT WE BRING TO THE FIELD",
    solutionTitle: "Every great harvest\nstarts with the right foundation.",
    solutionIntro:
      "Thoughtfully selected products. Trusted global partners. Everything connected to help your farm move forward.",
    categories: [
      {
        id: "seeds",
        label: "Seeds & genetics",
        description:
          "The starting point for a productive season. Vegetable and field crop seeds from established breeders.",
        detail:
          "Explore tomato, carrot and corn selections. Our team can help you discuss varieties for your growing conditions.",
        tag: "THE BEGINNING",
        brands: "Hazera · Enza Zaden · Fitó",
      },
      {
        id: "soil",
        label: "Soil & nutrition",
        description:
          "Build a stronger foundation with growing substrates and solutions for plant nutrition.",
        detail:
          "Discover cocopeat substrates from Dutch Plantin and nutrition solutions from Meristem. Ask our team about the available range.",
        tag: "THE FOUNDATION",
        brands: "Dutch Plantin · Meristem",
      },
      {
        id: "water",
        label: "Water & irrigation",
        description:
          "Connect your growing operation with practical piping and water distribution solutions.",
        detail:
          "Explore piping solutions from Pipelife for water distribution. Contact our team to discuss your project requirements.",
        tag: "THE CONNECTION",
        brands: "Pipelife",
      },
    ],
    elementEyebrow: "02 / A CONNECTED APPROACH",
    elementTitle: "Small elements.\nExtraordinary possibilities.",
    elementIntro:
      "Soil, water and nutrition work together. Explore the foundations behind our agricultural solutions.",
    elementLabels: ["Soil", "Water", "Nutrition"],
    elementDescriptions: [
      "A dependable growing medium is where it all begins. Explore substrates that support your growing operation.",
      "Bring water where it is needed. Explore piping and distribution solutions for your farm.",
      "Support the next stage of growth. Discover our partners’ plant nutrition solutions.",
    ],
    interactive: "DRAG TO ROTATE",
    scene: "Agricultural model",
    modelNames: [
      "Cultivated soil profile",
      "Drip irrigation assembly",
      "Granular fertilizer",
    ],
    modelControls: "Model view controls",
    rotateLeft: "Rotate left",
    rotateRight: "Rotate right",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    resetView: "Reset view",
    aboutEyebrow: "03 / OUR ROOTS",
    aboutTitle: "Global know-how.\nCloser to your fields.",
    aboutIntro: "We believe a strong harvest begins with a strong partnership.",
    aboutBody:
      "Established in Dushanbe in 2016, Nihol connects agricultural producers across Tajikistan with international manufacturers. Our regional distribution network brings products closer to the people who need them.",
    team: "Qualified team members",
    established: "The year our story began",
    network: "A network across Tajikistan",
    direct: "Direct manufacturer relationships",
    partnerEyebrow: "04 / STRONGER TOGETHER",
    partnerTitle: "Good company.\nBetter possibilities.",
    partnerIntro:
      "Meet the specialists behind our solutions. International expertise, brought closer to your farm.",
    contactEyebrow: "05 / THE NEXT CHAPTER",
    contactTitle: "Let’s grow\nsomething great.",
    contactIntro:
      "Follow new products and agricultural solutions from Nihol. Leave your email to stay connected.",
    email: "Your email address",
    subscribe: "Keep me informed",
    submitting: "Subscribing…",
    privacy: "Your email will be used for Nihol updates.",
    address: "Dushanbe, Tajikistan",
    street: "Sino district, R. Nabieva Street 218",
    footerLine: "Better connections. Stronger foundations.",
    catalogue: "The right start for your next season.",
    catalogueIntro:
      "Explore our agricultural solutions and the expertise behind them.",
    all: "All solutions",
    back: "Back to home",
    details: "Product information",
    close: "Close details",
    enquire: "Connect with Nihol",
    available:
      "Contact our team for varieties, specifications and availability.",
    cropNames: ["Tomato seeds", "Carrot seeds", "Corn seeds"],
    skip: "Skip to content",
    menu: "Navigation menu",
    more: "Explore solution",
  },
  ru: {
    solutions: "Наши решения",
    story: "О компании",
    partners: "Партнёры",
    contact: "Растём вместе",
    eyebrow: "ОБЪЕДИНЯЕМ АГРОВОЗМОЖНОСТИ.",
    title: "В основе — доверие.",
    accent: "Впереди — рост.",
    intro:
      "Соединяем аграриев Таджикистана с мировыми сельскохозяйственными решениями. От первого семени до нового урожая.",
    explore: "Открыть наши решения",
    discover: "Узнать о Nihol",
    scroll: "ЛИСТАЙТЕ И ОТКРЫВАЙТЕ",
    since: "РАЗВИВАЕМ ПАРТНЁРСТВО С 2016 ГОДА",
    pause: "Остановить анимацию",
    play: "Включить анимацию",
    trusted: "МИРОВОЙ ОПЫТ. МЕСТНЫЕ КОРНИ.",
    solutionEyebrow: "01 / РЕШЕНИЯ ДЛЯ ВАШИХ ПОЛЕЙ",
    solutionTitle: "Хороший урожай\nначинается с верной основы.",
    solutionIntro:
      "Тщательно подобранные продукты. Надёжные мировые партнёры. Всё, чтобы ваше хозяйство двигалось вперёд.",
    categories: [
      {
        id: "seeds",
        label: "Семена и генетика",
        description:
          "Начало продуктивного сезона. Семена овощных и полевых культур от известных селекционеров.",
        detail:
          "Ознакомьтесь с семенами томата, моркови и кукурузы. Наша команда поможет обсудить сорта для ваших условий выращивания.",
        tag: "НАЧАЛО",
        brands: "Hazera · Enza Zaden · Fitó",
      },
      {
        id: "soil",
        label: "Субстраты и питание",
        description:
          "Надёжная основа для роста: субстраты и решения для питания растений.",
        detail:
          "Кокосовые субстраты Dutch Plantin и решения для питания от Meristem. Уточните доступный ассортимент у нашей команды.",
        tag: "ОСНОВА",
        brands: "Dutch Plantin · Meristem",
      },
      {
        id: "water",
        label: "Вода и орошение",
        description:
          "Практичные трубопроводные решения для водоснабжения вашего хозяйства.",
        detail:
          "Трубопроводные решения Pipelife для распределения воды. Свяжитесь с нами, чтобы обсудить требования вашего проекта.",
        tag: "СВЯЗЬ",
        brands: "Pipelife",
      },
    ],
    elementEyebrow: "02 / КОМПЛЕКСНЫЙ ПОДХОД",
    elementTitle: "Малые элементы.\nБольшие возможности.",
    elementIntro:
      "Почва, вода и питание работают вместе. Откройте основы наших сельскохозяйственных решений.",
    elementLabels: ["Почва", "Вода", "Питание"],
    elementDescriptions: [
      "Всё начинается с надёжной среды для роста. Откройте субстраты для вашего хозяйства.",
      "Доставляйте воду туда, где она нужна. Изучите решения для трубопроводов и распределения воды.",
      "Поддержите следующий этап роста. Откройте решения наших партнёров для питания растений.",
    ],
    interactive: "ПЕРЕТАЩИТЕ ДЛЯ ВРАЩЕНИЯ",
    scene: "Сельскохозяйственная модель",
    modelNames: [
      "Разрез обработанной почвы",
      "Узел капельного орошения",
      "Гранулированное удобрение",
    ],
    modelControls: "Управление видом модели",
    rotateLeft: "Повернуть влево",
    rotateRight: "Повернуть вправо",
    zoomIn: "Приблизить",
    zoomOut: "Отдалить",
    resetView: "Сбросить вид",
    aboutEyebrow: "03 / НАШИ КОРНИ",
    aboutTitle: "Мировые знания.\nБлиже к вашим полям.",
    aboutIntro: "Мы верим: сильный урожай начинается с надёжного партнёрства.",
    aboutBody:
      "Основанная в Душанбе в 2016 году, компания Nihol соединяет аграриев Таджикистана с международными производителями. Региональная сеть дистрибуции доставляет продукцию ближе к тем, кому она нужна.",
    team: "Квалифицированных сотрудников",
    established: "Год начала нашей истории",
    network: "Сеть по всему Таджикистану",
    direct: "Прямые связи с производителями",
    partnerEyebrow: "04 / СИЛЬНЕЕ ВМЕСТЕ",
    partnerTitle: "Надёжные партнёры.\nНовые возможности.",
    partnerIntro:
      "Знакомьтесь со специалистами, стоящими за нашими решениями. Международный опыт — ближе к вашему хозяйству.",
    contactEyebrow: "05 / СЛЕДУЮЩАЯ ГЛАВА",
    contactTitle: "Вырастим\nбудущее вместе.",
    contactIntro:
      "Узнавайте о новой продукции и агрорешениях Nihol. Оставьте email, чтобы быть на связи.",
    email: "Ваш email",
    subscribe: "Быть в курсе",
    submitting: "Подписываем…",
    privacy: "Ваш email будет использоваться для новостей Nihol.",
    address: "Душанбе, Таджикистан",
    street: "Район Сино, ул. Р. Набиева, 218",
    footerLine: "Надёжные связи. Прочная основа.",
    catalogue: "Верное начало нового сезона.",
    catalogueIntro:
      "Откройте наши сельскохозяйственные решения и опыт наших партнёров.",
    all: "Все решения",
    back: "На главную",
    details: "О продукции",
    close: "Закрыть подробности",
    enquire: "Связаться с Nihol",
    available: "Уточняйте сорта, характеристики и наличие у нашей команды.",
    cropNames: ["Семена томата", "Семена моркови", "Семена кукурузы"],
    skip: "Перейти к содержимому",
    menu: "Меню навигации",
    more: "Подробнее",
  },
};
export const partners = [
  { name: "Hazera", logo: "/partners/hazera.svg", key: "Hazera" },
  { name: "Enza Zaden", logo: "/partners/enza.svg", key: "Enza Zaden" },
  { name: "Fitó", logo: "/partners/fit6.svg", key: "Fitó" },
  {
    name: "Dutch Plantin",
    logo: "/partners/dutch-plantin.svg",
    key: "Dutch Plantin",
  },
  { name: "Meristem", logo: "/partners/meristem.svg", key: "Meristem" },
  { name: "Pipelife", logo: "/partners/pipelife.svg", key: "Pipelife" },
];
